# Generated by Django 5.1.7 on 2025-03-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_email', models.EmailField(max_length=254, unique=True, verbose_name='Email менеджера')),
            ],
            options={
                'verbose_name': 'Настройки менеджера',
                'verbose_name_plural': 'Настройки менеджера',
            },
        ),
    ]
